server:
  port: 8888 #修改tomcat的默认的端口号，将8080改为8888
  #context-path: /cms
  #error:
  #  path: /error # 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
  #session-timeout: 60 # session最大超时时间(分钟)，默认为30
  #address: 192.168.0.3 # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置

#spring:
#  data:
#    mongodb:
#      host: 192.168.0.111
#      port: 27017
#      database: cms

spring:
  datasource:
    url: 'jdbc:mysql://182.92.128.240:3306/smartparkapp?characterEncoding=utf-8'
    username: 'root'
    password: 'a'
    driverClassName: 'com.mysql.jdbc.Driver'

#本项目的自定义配置
cms:
  houoy: www.houoy.com
  date: 2017-02-21
  localFilePath: F:/

#nginx:
#  url: 47.94.6.120
#  port: 22
#  user: root
#  pass: Andy891014@
#  path: /usr/local/nginx/html/image
#  pathVideo: /usr/local/nginx/html/video
#  pathApk: /usr/local/nginx/html/apk

nginx:
  url: localhost
  port: 22
  user: andyzhao
  pass: iandtop
  path: H:\soft\nginx\nginx-1.12.0\html\image
  pathVideo: H:\soft\nginx\nginx-1.12.0\html\video
  pathApk: H:/soft/nginx/nginx-1.12.0/html/
  httpUrl: http://192.168.0.100:80/

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
